services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-yourRedisPassword}"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
