# Use an official Node runtime as a parent image
FROM node:18-alpine AS base

# Set working directory
WORKDIR /app

# Install dependencies first for caching purposes
COPY package*.json ./
RUN npm install 

# Copy the rest of the code
COPY . .

# Expose the backend port
EXPOSE 5000



# Run the application
CMD ["npm", "start"]
